# Generated by Django 4.2.8 on 2026-03-23 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HotelApp', '0008_authorregis_is_receptionist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(max_length=50, unique=True)),
                ('is_online', models.BooleanField(default=True)),
                ('simulation_enabled', models.BooleanField(default=True)),
                ('temperature_min_normal', models.FloatField(default=20.0)),
                ('temperature_max_normal', models.FloatField(default=27.5)),
                ('gas_warning_threshold', models.PositiveIntegerField(default=70)),
                ('gas_critical_threshold', models.PositiveIntegerField(default=120)),
                ('sampling_interval_seconds', models.PositiveIntegerField(default=45)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iot_device', to='HotelApp.room')),
            ],
            options={
                'ordering': ['room__floor', 'room__room_number'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField()),
                ('gas_level', models.PositiveIntegerField(help_text='Simulated gas concentration in ppm.')),
                ('motion_state', models.CharField(choices=[('idle', 'Idle'), ('brief', 'Brief Movement'), ('active', 'Active Movement'), ('tamper', 'Tamper / Forced Entry')], default='idle', max_length=20)),
                ('occupancy_expected', models.BooleanField(default=False)),
                ('overall_status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('simulated', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='alerts.iotdevice')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='HotelApp.room')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomConditionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temperature', 'Temperature'), ('gas', 'Gas Leakage'), ('motion', 'Unexpected Motion'), ('device', 'Device Health')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_room_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.iotdevice')),
                ('latest_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_alerts', to='alerts.sensorreading')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_alerts', to='HotelApp.room')),
            ],
            options={
                'ordering': ['-is_active', '-triggered_at'],
            },
        ),
    ]
