# Generated by Django 4.2.8 on 2026-03-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomconditionalert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='roomconditionalert',
            name='last_notified_severity',
            field=models.CharField(blank=True, choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=20),
        ),
        migrations.AddField(
            model_name='roomconditionalert',
            name='notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomconditionalert',
            name='resolution_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('triggered', 'Triggered'), ('escalated', 'Escalated'), ('reminder', 'Reminder'), ('resolved', 'Resolved')], db_index=True, max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('simulated', 'Simulated'), ('failed', 'Failed')], db_index=True, default='simulated', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.roomconditionalert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
