"""
Django settings for HotelManagementSystem project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import dj_database_url


def load_env_files(*paths):
    for path in paths:
        if not path or not Path(path).exists():
            continue
        for raw_line in Path(path).read_text().splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name, default):
    try:
        return int(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default


def env_float(name, default):
    try:
        return float(os.environ.get(name, str(default)))
    except (TypeError, ValueError):
        return default

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_env_files(BASE_DIR / '.env', BASE_DIR / 'iot_alerts.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY: Secret key from environment (required in production)
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-only-change-in-production')

# SECURITY: Debug mode from environment (defaults to False for safety)
DEBUG = env_bool('DEBUG', False)

# SECURITY: Allowed hosts - explicitly configured
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# SECURITY: CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

AUTH_USER_MODEL = 'HotelApp.Authorregis'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'HotelApp',
    'alerts',
]

LOGIN_URL = '/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HotelManagementSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HotelManagementSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "Project_hotel"}',
        conn_max_age=60,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'alerts@rosegoldhotel.local')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = env_int('EMAIL_PORT', 587)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)

IOT_MONITOR_AUTOSTART = env_bool('IOT_MONITOR_AUTOSTART', DEBUG)
IOT_MONITOR_INTERVAL_SECONDS = env_int('IOT_MONITOR_INTERVAL_SECONDS', 30)
IOT_ALERT_REMINDER_MINUTES = env_int('IOT_ALERT_REMINDER_MINUTES', 10)
IOT_ALERT_EMAIL_ENABLED = env_bool('IOT_ALERT_EMAIL_ENABLED', True)
IOT_ALERT_SMS_ENABLED = env_bool('IOT_ALERT_SMS_ENABLED', True)
IOT_ALERT_SMS_BACKEND = os.environ.get('IOT_ALERT_SMS_BACKEND', 'console')
IOT_SIM_ABNORMAL_ROOM_RATE = env_float('IOT_SIM_ABNORMAL_ROOM_RATE', 0.20)
IOT_ALERT_EXTRA_EMAIL_RECIPIENTS = [
    email.strip()
    for email in os.environ.get('IOT_ALERT_EXTRA_EMAIL_RECIPIENTS', '').split(',')
    if email.strip()
]
IOT_ALERT_EXTRA_SMS_RECIPIENTS = [
    number.strip()
    for number in os.environ.get('IOT_ALERT_EXTRA_SMS_RECIPIENTS', '').split(',')
    if number.strip()
]
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.environ.get('TWILIO_FROM_NUMBER', '')

DEFAULT_RECEPTIONIST_EMAIL = os.environ.get('DEFAULT_RECEPTIONIST_EMAIL', '').strip()
DEFAULT_RECEPTIONIST_PASSWORD = os.environ.get('DEFAULT_RECEPTIONIST_PASSWORD', '')
DEFAULT_RECEPTIONIST_FIRST_NAME = os.environ.get('DEFAULT_RECEPTIONIST_FIRST_NAME', 'Reception')
DEFAULT_RECEPTIONIST_LAST_NAME = os.environ.get('DEFAULT_RECEPTIONIST_LAST_NAME', 'Desk')
DEFAULT_RECEPTIONIST_PHONE = os.environ.get('DEFAULT_RECEPTIONIST_PHONE', '').strip()
DEFAULT_RECEPTIONIST_THEME = os.environ.get('DEFAULT_RECEPTIONIST_THEME', 'light').strip() or 'light'
DEFAULT_RECEPTIONIST_IS_ACTIVE = env_bool('DEFAULT_RECEPTIONIST_IS_ACTIVE', True)
DEFAULT_RECEPTIONIST_SYNC_PASSWORD = env_bool('DEFAULT_RECEPTIONIST_SYNC_PASSWORD', True)


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

WHITENOISE_MANIFEST_STRICT = False
STATIC_URL = '/static/'
STATICFILES_DIRS =[
  os.path.join (BASE_DIR / 'static')
]
STATIC_ROOT = os.path.join (BASE_DIR,'assets')
if 'test' in sys.argv:
    STATIC_ROOT = os.path.join(BASE_DIR, '.test-static')
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================
# SECURITY SETTINGS
# =========================

# SECURITY: Session and cookie settings
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 hours (reduced from 7 days for better security)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'

# SECURITY: HTTP Strict Transport Security (HSTS)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# SECURITY: Additional headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# SECURITY: SSL redirect in production
SECURE_SSL_REDIRECT = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SECURITY: Referrer policy
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# =========================
# PERFORMANCE SETTINGS
# =========================

# Database connection pooling (already configured via dj-database-url)
# conn_max_age=60 and conn_health_checks=True are set above

# Caching configuration
REDIS_URL = os.environ.get('REDIS_URL', '')

if REDIS_URL and not DEBUG:
    # Production: Use Redis for caching
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'rosegold',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    # Development: Use local memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'rosegoldhotels-cache',
            'TIMEOUT': 300,
        }
    }

# Template caching in production
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]
    # Remove APP_DIRS when using loaders
    TEMPLATES[0]['APP_DIRS'] = False

# =========================
# LOGGING CONFIGURATION
# =========================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'HotelApp': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# =========================
# PAYSTACK CONFIGURATION
# =========================

# Payment gateway keys - MUST be set via environment in production
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', '')
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', '')
PAYSTACK_WEBHOOK_SECRET = os.environ.get('PAYSTACK_WEBHOOK_SECRET', '')
PAYSTACK_API_BASE_URL = os.environ.get('PAYSTACK_API_BASE_URL', 'https://api.paystack.co')
PAYSTACK_CURRENCY = os.environ.get('PAYSTACK_CURRENCY', 'NGN')

# Development warning for missing payment keys
if not PAYSTACK_PUBLIC_KEY and DEBUG:
    import warnings
    warnings.warn(
        "PAYSTACK_PUBLIC_KEY not set. Payment functionality will not work. "
        "Get your keys from: https://dashboard.paystack.com/#/settings/developer"
    )

# =========================
# FILE UPLOAD SECURITY
# =========================

DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB max upload
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB max file

