# Generated by Django 4.2.28 on 2026-03-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0004_alter_room_image_alter_room_room_type'),
        ('HotelApp', '0004_authorregis_theme'),
    ]

    operations = [
    ]
