# Generated by Django 6.0.3 on 2026-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_merge_20260315_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinebooking',
            name='check_in',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='offlinebooking',
            name='check_out',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='check_in',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='check_out',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20),
        ),
    ]
